### ISSUE TITLE
Update Privacy Policy with more details about Discord information

### ISSUE THREAD

**Issue by tjrgg** [typicalbot/policies#3]
With the merge of discord/discord-api-docs#1870, I'd like to update our policy to more expressly state what information we use and store from Discord users, why we use it and who has access to it.

**Comment by nsylke** [comment]
As of 3.x we store the following:
 - User generated content when editing certain settings (welcome message, custom logs, etc.)
 - User id, message id, channel id, guild id, timestamp, command and command arguments for analytics
 - Guild id, channel id, and role ids for various settings

I work on a list for 4.x in a separate comment as I will need to look throughout the various repositories and upcoming features.
